baseurl = "http://xmruibi.github.io/"
languageCode = "en-us"
title = "Geek Think"

# Copyright
copyright = "(c) 2015 Rui Bi."


# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "toml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hugo-icarus-theme"

# Pagination
paginate = 15

# Enable Disqus integration
disqusShortname = "ruisblog"

[pages]
    tag = "tags"
    topics = "topics"
    
[permalinks]
    post = "/:year/:month/:day/:slug/"
    project = "/:year/:month/:day/:slug/"
    life = "/:year/:month/:day/:slug/"

[taxonomies]
    tag = "tags"
    topics = "topics"

[params]
    author = "Rui's Blog"
    email = "xmruibi@gmail.com"
    bio = "A Thinker, A Programmer, A Traveller"
    location = "California - Bay Area"
    site_description = ""
    copyright  = "(c) 2015 Rui Bi. Powered by [Hugo](//gohugo.io)."
    date_format = "2006-01-02"
    googleAnalytics = "UA-69058903-1"


[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

[[params.menu]]
    before = false
    label  = "Project"
    link   = "code/"

[[params.menu]]
    before = false
    label  = "Life"
    link   = "life/"

[[params.menu]]
    before = false
    label  = "Tags"
    link   = "tags/"

[[params.menu]]
    before = false
    label  = "About"
    link   = "about"

    

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://github.com/xmruibi"

[social]
    github      = "xmruibi" 
    linkedin    = "ruibi" 

[params.widgets]
    recent_articles = true
    topics = true

